[build]
    builder = "nixpacks"

[phases.setup]
    nixPkgs = ["nodejs", "python3"]
    cmds = ["npm install", "pip install -r scraps/memories/requirements.txt"]

[phases.build]
    cmds = []

[start]
    cmd = "node llm/server.js & python scraps/memories/run.py"
